### ISSUE TITLE
[Meta] Roadmap

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#5]
**Goals**

- Translate Backdrop CMS core
- Host translations of Backdrop CMS core
- Host Translations Backdrop contributed projects (someday soon)
- Host translations of Backdrop contributed projects (someday soon)

**General Tasks**

- [x] Basic configuration of the translation server. (Issue #1)
- [x] Test the server with Drupal language files. (Issue #1)
- [x] Test the server with Backdrop language files. (Issue https://github.com/backdrop-ops/localization/issues/1#issuecomment-282898445)
- [x] Generate English language files (Issue #6);
Backdrop's English language files (which change from release to release) are needed as template for translations. At the moment, it's possible to extract language strings using the *potx* module -- see also the [potx issue queue](https://github.com/backdrop-contrib/potx/issues).  
- [ ] Automate the extraction of language strings for every release. https://github.com/backdrop-ops/localize.backdropcms.org/issues/6
- [ ] Develop a translation concept, including participation of community members. (Doing, see Issue #7)

**Contribution and Documentation Tasks**

- [x] Add a role and permissions for community members. (Issue #7)
- [ ] Update translation & language relevant documentation for Backdrop CMS.
